### ISSUE TITLE
Option to choose an opponent between AI or Player 

### ISSUE THREAD

**Issue by MKon55** [MKon55/Ceska_dama_2022#11]
- [x] AI x P1

- [x] P1 x P2 

Možnost udělat AI x AI? 
- Jak budeme chtít ale myslím že není potřeba

**Comment by MKon55** [comment]
Main menu implemented 
NOW => in game option

**Comment by thund-6** [comment]
AI a AI bych dal na backburner

**Comment by MKon55** [comment]
Options done and working
